Change to 'machine' as 'docker' on CircleCI does not support --privileged mode

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,14 +2,13 @@
 version: 2.1
 jobs:
   build-and-scan-image:
-    docker: 
-      - image: docker:dind
+    machine:
+      image: ubuntu-1604:201903-01
     steps:
       - checkout
-      - setup_remote_docker
-      - run: 
-          name: Install scanning dependencies
-          command: apk update && apk add -U wget ca-certificates lsof
+        #      - run: 
+        #          name: Install scanning dependencies
+        #          command: apt update -y && apk install -y wget ca-certificates
       - run:
           name: Build Docker image
           command: docker build -t ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
@@ -34,18 +33,15 @@ jobs:
           name: Scan docker image for vulnerabilities
           command: | 
             echo "Waiting for Clair DB to start"
-            lsof
-            #while( ! wget -q -O /dev/null http://localhost:6060/v1/namespaces ) ; do sleep 1 ; echo -n "." ; done
+            while( ! wget -q -O /dev/null http://localhost:6060/v1/namespaces ) ; do sleep 1 ; echo -n "." ; done
             retries=0
             echo "Waiting for Clair daemon to be ready for scanning"
-            #while( ! wget -T 10 -q -O /dev/null http://localhost:6060/v1/namespaces ) ; do sleep 1 ; echo -n "." ; if [ $retries -eq 10 ] ; then echo " Timeout, aborting." ; exit 1 ; fi ; retries=$(($retries+1)) ; done
-            sleep 20
+            while( ! wget -T 10 -q -O /dev/null http://localhost:6060/v1/namespaces ) ; do sleep 1 ; echo -n "." ; if [ $retries -eq 10 ] ; then echo " Timeout, aborting." ; exit 1 ; fi ; retries=$(($retries+1)) ; done
             ./clair-scanner -c http://localhost:6060 --ip $(hostname -i) -r container-scanning-report.json -l clair.log -w clair-whitelist.yml ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} || true
   release-image:
-    docker: 
-      - image: docker:dind
+    machine:
+      image: ubuntu-1604:201903-01
     steps:
-      - setup_remote_docker
       - run:
           name: Release approved Docker image
           command: |
